    --powerview.ps1 usage--
powershell
__________________________________________________________________________________________________
__________________________________________________________________________________________________
powershell.exe -nop -exec bypass
Import-Module [full path to powerview.ps1]
__________________________________________________________________________________________________
__________________________________________________________________________________________________
alternative --> powershell -ep bypass
. .\PowerView.ps1
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Current Domain: 
Get-NetDomain
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Other Domains: 
Get-NetDomain -Domain <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Domain SID: 
Get-DomainSID
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Domain Policy:
Get-DomainPolicy
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Will show us the policy configurations of the Domain about system access or kerberos
(Get-DomainPolicy)."system access"
(Get-DomainPolicy)."kerberos policy"
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Domain Controlers:
Get-NetDomainController
Get-NetDomainController -Domain <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Domain Users:
Get-NetUser
Get-NetUser -SamAccountName <user> 
Get-NetUser | select cn
Get-UserProperty
Get-NetUser | select description
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Check last password change
Get-UserProperty -Properties pwdlastset
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get a specific "string" on a user's attribute
Find-UserField -SearchField Description -SearchTerm "wtver"
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate user logged on a machine
Get-NetLoggedon -ComputerName <ComputerName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Session Information for a machine
Get-NetSession -ComputerName <ComputerName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate domain machines of the current/specified domain where specific users are logged into
Find-DomainUserLocation -Domain <DomainName> | Select-Object UserName, SessionFromName
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Domain Computers:
Get-NetComputer -FullData
Get-DomainGroup
Get-NetComputer
Get-NetComputer | select operatingsystem
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Live machines 
Get-NetComputer -Ping
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Groups and Group Members:
Get-NetGroup
Get-NetGroup | select name
Get-NetGroupMember -GroupName "<GroupName>" -Domain <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate the members of a specified group of the domain
Get-DomainGroup -Identity <GroupName> | Select-Object -ExpandProperty Member
    If we want to get all the groups a user is a member of
Get-DomainGroup -MemberIdentity username | select cn
Get-DomainGroup -MemberIdentity username | select samaccountname
Get-DomainGroupMember -Identity "Domain Admins" -Recurse
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Returns all GPOs in a domain that modify local group memberships through Restricted Groups or Group Policy Preferences
Get-DomainGPOLocalGroup | Select-Object GPODisplayName, GroupName
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Shares:
    Enumerate Domain Shares
Find-DomainShare
Invoke-ShareFinder
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Domain Shares the current user has access
Find-DomainShare -CheckShareAccess
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Group Policies:
Get-NetGPO
Get-NetGPO | select displayname, whenchanged, whencreated
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Shows active Policy on specified machine
Get-NetGPO -ComputerName <Name of the PC>
Get-NetGPOGroup
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get users that are part of a Machine's local Admin group
Find-GPOComputerAdmin -ComputerName <ComputerName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum OUs:
Get-NetOU -FullData 
Get-NetGPO -GPOname <The GUID of the GPO>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum ACLs:
    Returns the ACLs associated with the specified account
Get-ObjectAcl -SamAccountName <AccountName> -ResolveGUIDs
Get-ObjectAcl -ADSprefix 'CN=Administrator, CN=Users' -Verbose
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Search for interesting ACEs
Invoke-ACLScanner -ResolveGUIDs
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Check the ACLs associated with a specified path (e.g smb share)
Get-PathAcl -Path "\\Path\Of\A\Share"
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Domain Trust:
Get-NetDomainTrust
Get-NetDomainTrust -Domain <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Forest Trust:
Get-NetForestDomain
Get-NetForestDomain Forest <ForestName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Domains of Forest Enumeration
Get-NetForestDomain
Get-NetForestDomain Forest <ForestName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Map the Trust of the Forest
Get-NetForestTrust
Get-NetDomainTrust -Forest <ForestName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    User Hunting:
    Finds all machines on the current domain where the current user has local admin access
Find-LocalAdminAccess -Verbose
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Find local admins on all machines of the domain:
Invoke-EnumerateLocalAdmin -Verbose
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Find computers were a Domain Admin OR a specified user has a session
Invoke-UserHunter
Invoke-UserHunter -GroupName "RDPUsers"
Invoke-UserHunter -Stealth
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Confirming admin access:
Invoke-UserHunter -CheckAccess
    If you wanted to check if the current user context has local administrator access
Invoke-CheckLocalAdminAccess
    If you wanted to check if the current user has administrative access to the local (or a remote) machine
Test-AdminAccess
__________________________________________________________________________________________________
__________________________________________________________________________________________________
                                    Using AD Module
    Get Current Domain: 
Get-ADDomain
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Other Domains: 
Get-ADDomain -Identity <Domain>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Domain SID: 
Get-DomainSID
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Get Domain Controlers:
Get-ADDomainController
Get-ADDomainController -Identity <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enumerate Domain Users:
Get-ADUser -Filter * -Identity <user> -Properties *

    Get a specific "string" on a user's attribute
Get-ADUser -Filter 'Description -like "*wtver*"' -Properties Description | select Name, Description
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Domain Computers:
Get-ADComputer -Filter * -Properties *
Get-ADGroup -Filter * 
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Domain Trust:
Get-ADTrust -Filter *
Get-ADTrust -Identity <DomainName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Forest Trust:
Get-ADForest
Get-ADForest -Identity <ForestName>
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Domains of Forest Enumeration
(Get-ADForest).Domains
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Enum Local AppLocker Effective Policy:
Get-AppLockerPolicy -Effective | select -ExpandProperty RuleCollections
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    User Hunting
Sometimes you need to find a machine where a specific user is logged in.
You can remotely query every machines on the network to get a list of the users's sessions.

    netexec

nxc smb 10.10.10.0/24 -u Administrator -p 'P@ssw0rd' --sessions
SMB         10.10.10.10    445    WIN-8OJFTLMU1IG  [+] Enumerated sessions
SMB         10.10.10.10    445    WIN-8OJFTLMU1IG  \\10.10.10.10            User:Administrator
__________________________________________________________________________________________________
__________________________________________________________________________________________________
Impacket Smbclient

$ impacket-smbclient Administrator@10.10.10.10
# who
host:  \\10.10.10.10, user: Administrator, active:     1, idle:     0
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    PowerView Invoke-UserHunter

    # Find computers were a Domain Admin OR a specified user has a session
    Invoke-UserHunter
    Invoke-UserHunter -GroupName "RDPUsers"
    Invoke-UserHunter -Stealth
__________________________________________________________________________________________________
__________________________________________________________________________________________________
    Other Interesting Commands
    Find Domain Controllers

nslookup domain.com
nslookup -type=srv _ldap._tcp.dc._msdcs.<domain>.com
nltest /dclist:domain.com
Get-ADDomainController -filter * | Select-Object name
gpresult /r
$Env:LOGONSERVER 
echo %LOGONSERVER%
